CREATE TABLE IF NOT EXISTS meta_medicaments (
    id SERIAL PRIMARY KEY,
    name text,
    presentation text,
    description text,
    classification text,
    drug_leaflet text,
    medicament_type text,
    defined_price boolean,
    high_cost boolean,
    price double precision,
    min_price double precision,
    max_price double precision,
    special_control boolean,
    prescription text,
    type text,
    category text,
    indications text,
    pediatric_dosage text,
    adults_dosage text,
    elderly_dosage text,
    adverse_reactions text,
    contraindications text,
    pregnancy text,
    lactation text,
    recommendations text,
    exams text,
    posology text,
    composition text,
    characteristics text,
    physical_form text,
    administration_via character varying(255),
    is_deleted boolean NOT NULL DEFAULT false,
    ans character varying(25) DEFAULT NULL::character varying,
    indice_pesquisa tsvector,
    opensearch_index character varying(255),
    is_antimicrobial boolean DEFAULT false
);
